Dimension of Array

In [3]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim,b.ndim,c.ndim,d.ndim)


0 1 2 3


In [4]:
a

array(42)

In [5]:
b

array([1, 2, 3, 4, 5])

In [6]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
# dimension of array is given by array.ndim()

Basic Characterstics

In [14]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
a = np.arange(10)
print(a)
print(a[5:])
print(a[::-1])

<class 'numpy.ndarray'>
2
(2, 3)
6
int64
[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [15]:
k = np.array((45,56,7,5))

In [16]:
k

array([45, 56,  7,  5])

In [17]:
q = np.array([[1,2,3],[4,5,6]])

In [18]:
q

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
print(q[0,0])
print(q[0,-1])
print(q[0,:])
print(q[:,0])

1
3
[1 2 3]
[1 4]


In [34]:
j = np.zeros((4,3))

In [35]:
j

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
g = np.ones((4,3))

In [39]:
g

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
g = np.identity(3)

In [41]:
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
g = np.random.randint(4,10,6)

In [47]:
g

array([7, 4, 4, 6, 5, 6])

In [70]:
f = np.eye(4,k=-2)

In [71]:
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])